- name: disbale Transparent Huge Pages
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: true
  tags:
    - hardening

- name: adjust vmswappiness
  sysctl: name=vm.swappiness value=1 state=present ignoreerrors=yes
  tags:
    - hardening

- name: start NetworkManager
  service: name=NetworkManager state=restarted enabled=true
  tags:
    - hardening

- name: disable firewall service
  service: name=firewalld state=stopped enabled=false
  tags:
    - hardening

- name: disable selinux
  selinux:
    state: disabled
  register: task_result
  tags:
    - hardening

- name: Reboot immediately to apply selinux status as disabled.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed
  tags:
    - hardening

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed
  tags:
    - hardening

- name: Secure Boot Settings
  file:
    path: /boot/grub2/grub.cfg
    mode: o-rwx,g-rwx
  tags:
    - hardening

#- name: Set bootloader password 

# - name: disable unwanted services

- name: remove prelink tool
  yum: name=prelink state=absent
  tags:
    - hardening
